apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-backend
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
